### ISSUE TITLE
Nuget package - SEO Integration

### ISSUE THREAD

**Issue by Drosty** [bazaarvoice/HostedUIResources#28]
For convenience, It would be nice to have a Nuget package for the SEO Integration DLL.

**Comment by ltanbv** [comment]
Thanks for reaching out. Our updated SEO integration docs have moved to our [Knowledgebase](http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/KB/Default.htm#SEO/SEO_About.htm), so we are no longer updating SDK information here. If you require any integration assistance, please contact your implementation team or reach out to our support team via [Spark](http://spark.bazaarvoice.com) or support@bazaarvoice.com.

Closing due to age and SEO docs have moved.
