### ISSUE TITLE
bvclient.properties - Resource not found exception

### ISSUE THREAD

**Issue by kmkrishna** [bazaarvoice/HostedUIResources#36]
We are using Websphere Commerce 7 and wanted to integrate Bazaarvoice SEO for our company. We downloaded the JAR file and tried to make some changes in our functionality to utilise the SEO feature. However, we are having problems with one of the property files(bvclient.properties). We tried copying this properties file into our standard libraries, but the files is not found when we execute the JAR. We are getting the following error message.

"com.bazaarvoice.Configuration <clinit> Unable to find bvclient.properties file in path.  Some required properties are not defined".

Please suggest

**Comment by ltanbv** [comment]
Thanks for reaching out. Our updated SEO integration docs have moved to our [Knowledgebase](http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/KB/Default.htm#SEO/SEO_About.htm), so we are no longer updating SDK information here. If you require any integration assistance, please contact your implementation team or reach out to our support team via [Spark](http://spark.bazaarvoice.com) or support@bazaarvoice.com.

Closing due to age and SEO docs have moved.
