### ISSUE TITLE
DotNet SDK - Property Flag to know whether the request processed was a search bot or not.

### ISSUE THREAD

**Issue by export-mike** [bazaarvoice/HostedUIResources#49]
Hi,

It would be very useful if the .net library had a property IsSearchBotRequest. Due to the method in which you return the javascript. In ASP.NEt webforms we use a script manager for all of our scripts. This returned javascript is incompatible. But by having a flag to know whether the request processed was a search bot or not would allow me to render the read reviews script in the method we are currently. 

We have no way of telling whether the request was made from a search bot or not.

I have taken the initiative to make the change which can be seen here:
https://github.com/mikeljames/bazaarvoice-HostedUIResources

Is it possible to make this a pull request? The change is very minimal.

Thanks,

Mike

**Comment by ltanbv** [comment]
Thanks for reaching out. Our updated SEO integration docs have moved to our [Knowledgebase](http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/KB/Default.htm#SEO/SEO_About.htm), so we are no longer updating SDK information here. If you require any integration assistance, please contact your implementation team or reach out to our support team via [Spark](http://spark.bazaarvoice.com) or support@bazaarvoice.com.

Closing due to age and SEO docs have moved.
