### ISSUE TITLE
Information Disclosure Issue

### ISSUE THREAD

**Issue by DaveSteff** [bazaarvoice/HostedUIResources#51]
Hi, 

should the seo file not exist locally, the call to getSeoResults > getFile (line 117) with throw a FileNotFound exception, which can include local website structure,

This detail is then returned directly to the page as a comment via getBvComment ( line 133).

I would recommend that the exception details be pushing instead to the _exception field, and hidden nicely in getBvComment, only revealed to the page if isBvRevealADebug.

Cheers
Dave.

**Comment by ltanbv** [comment]
Thanks for reaching out. Our updated SEO integration docs have moved to our [Knowledgebase](http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/KB/Default.htm#SEO/SEO_About.htm), so we are no longer updating SDK information here. If you require any integration assistance, please contact your implementation team or reach out to our support team via [Spark](http://spark.bazaarvoice.com) or support@bazaarvoice.com.

Closing due to age and SEO docs have moved.
