### ISSUE TITLE
bv.root.folder in debug parameters is confusing

### ISSUE THREAD

**Issue by tonypconway** [bazaarvoice/HostedUIResources#57]
https://github.com/bazaarvoice/HostedUIResources/blob/master/SEOIntegration/examples/php/bvseosdk.php#L451

If BV is asking clients for deployment_zone_id in the config parameters, it's really confusing in the debug output to refer to this as bv.root.folder - see line 451.  Would be good to update this for future versions.

**Comment by ltanbv** [comment]
Thanks for reaching out. Our updated SEO integration docs have moved to our [Knowledgebase](http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/KB/Default.htm#SEO/SEO_About.htm), so we are no longer updating SDK information here. If you require any integration assistance, please contact your implementation team or reach out to our support team via [Spark](http://spark.bazaarvoice.com) or support@bazaarvoice.com.

Closing due to age and SEO docs have moved.
