### ISSUE TITLE
Fatal error: Call to undefined method Reviews::renderSeo() 

### ISSUE THREAD

**Issue by kharbat** [bazaarvoice/HostedUIResources#71]
In PHP SDK I get this error when I follow the READ.md: 
Fatal error: Call to undefined method Reviews::renderSeo() 

However I can see the method getContent() in line 668, and it's working. Does it do the same thing?

**Comment by smallmtn** [comment]
getContent() would be the same as the original renderSEO().  getAggregate() and getReviews() are other options.

**Comment by ltanbv** [comment]
Thanks for reaching out. Our updated SEO integration docs have moved to our [Knowledgebase](http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/KB/Default.htm#SEO/SEO_About.htm), so we are no longer updating SDK information here. If you require any integration assistance, please contact your implementation team or reach out to our support team via [Spark](http://spark.bazaarvoice.com) or support@bazaarvoice.com.

Closing due to age and SEO docs have moved.
