### ISSUE TITLE
PHP notices for uninitialized variables assumed to have value

### ISSUE THREAD

**Issue by mbopp** [bazaarvoice/HostedUIResources#75]
I am getting the following notices when using the php seo sdk.  I realize 'notices' themselves do not cause problems, but are there to write better code.

```
Notice: Undefined variable: bvparam in Base->_getPageNumber() (line 372 of ~/bvseosdk.php).
Notice: Undefined offset: 1 in Base->_getPageNumber() (line 373 of ~/bvseosdk.php).
Notice: Undefined variable: bvparam in Base->_getPageNumber() (line 376 of ~/bvseosdk.php).
```

If I am doing something wrong, please let me know.

**Comment by ltanbv** [comment]
Thanks for reaching out. Our updated SEO integration docs have moved to our [Knowledgebase](http://knowledge.bazaarvoice.com/wp-content/conversations/en_US/KB/Default.htm#SEO/SEO_About.htm), so we are no longer updating SDK information here. If you require any integration assistance, please contact your implementation team or reach out to our support team via [Spark](http://spark.bazaarvoice.com) or support@bazaarvoice.com.

Closing due to age and SEO docs have moved.
